### ISSUE TITLE
packages.json: URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by Ambroz91** [ucan-lab/docker-laravel#253] opened 2024-02-21 13:15 UTC
Hello.
Trying to generate a new project, when using the command:
**docker compose exec app composer create-project --prefer-dist laravel/laravel .**
I've got this error:
**In CurlDownloader.php line 372:
/packages.json: URL using bad/illegal format or missing URL**
![obraz](https://github.com/ucan-lab/docker-laravel/assets/110357972/49bee392-b428-48bc-8c69-85b3c493c482)

Please help and thanks.

**Comment by Ambroz91** [comment] 2024-02-23 11:34
Hello.
There is an error in the composer/config.json file where the url is invalid due to **\r** present in the link.
Removing the characters makes that everything works.

**Comment by ucan-lab** [comment] 2024-05-01 17:08
Currently Actions in laravel-create-project.yml workflow in main branch is successful.

https://github.com/ucan-lab/docker-laravel/actions/workflows/laravel-create-project.yml?query=branch%3Amain

I couldn't reproduce this error even in my local environment, so I'll close it.
If you have any questions, please reopen and ask.

**Closed by ucan-lab** 2024-05-01 17:08 UTC
